SELECT * FROM Fact_Teachings;
SELECT * FROM Fact_Enrollment;
SELECT * FROM Dim_Course;
SELECT * FROM Dim_Faculty;
SELECT * FROM Dim_Tutor;
SELECT * FROM Dim_Date;
SELECT * FROM Dim_Time;
SELECT * FROM Dim_Student;
SELECT * FROM Dim_Survey;